version: "3"
services:
  api:
    build: ./services/server
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: test-api
  client:
    build: ./services/client
    ports:
      - "80:80"
    container_name: test-client